version: "3.7"

networks:
  default:
    external: true
    name:
      local

services:
  postgres:
    image: postgres:14
    container_name: app_postgre
    ports:
      - 3111:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Jakarta"
      PGTZ: "Asia/Jakarta"
    volumes:
      - ../db-data:/var/lib/postgresql/data    
  
  adminer:
    image:  "adminer"
    container_name: app_adminer
    ports:
      - 8080:8080

  redis:
    image: redis:alpine
    container_name: app_redis
    ports:
      - 6379:6379
    environment:
      TZ: "Asia/Jakarta"
      PGTZ: "Asia/Jakarta"
