version: "3.7"

networks:
  default:
    external:
      name:
        local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: app
    volumes:
      - ../.:/var/www
      - /var/www/node_modules
    ports:
      - 3000:3000
    command: "npm run dev"
