# syntax=docker/dockerfile:1

FROM node:16.14.2

ENV NODE_ENV=development

WORKDIR /var/www

COPY ["package.json", "./"]

RUN npm install --production --no-optional

COPY ../. .

RUN npm uninstall bcrypt

RUN npm install bcrypt

EXPOSE 3000

CMD [ "npm", "run", "dev" ]
